namespace Swate.Components.Page.Metadata

open Feliz
open Fable.Core
open ProcessCore
open Swate.Components.Page.Metadata
open Swate.Components.Page.ObjectBrowser.Types
open Swate.Components.Primitive.LayoutComponents
open Swate.Components.Page.Metadata.FormComponents
open Swate.Components.Shared

[<Erase; Mangle(false)>]
type DataContextMetadata =

    [<ReactComponent(true)>]
    static member DataContextView
        (
            dataContext: ProcessCore.DataContext,
            setDataContext: ProcessCore.DataContext -> unit,
            ?onNavigate: ProcessCoreEntityValue -> unit
        ) =

        let navigate = defaultArg onNavigate ignore

        LayoutComponents.Section [
            LayoutComponents.BoxedField(
                "Data Context Metadata",
                content = [
                    NestedMetadataInput.RequiredRow(
                        "Data",
                        dataContext.Data,
                        NestedMetadataInput.Data,
                        (ProcessCoreEntityValue.Data >> navigate)
                    )
                    (NestedMetadataInput.OptionalDefinedTerm(
                        "Explication",
                        dataContext.Explication,
                        (fun value -> dataContext.Copy(explication = value) |> setDataContext),
                        (ProcessCoreEntityValue.DefinedTerm >> navigate),
                        imports = (fun catalog -> catalog.DefinedTerms)
                    ))
                    (NestedMetadataInput.OptionalDefinedTerm(
                        "Object Type",
                        dataContext.ObjectType,
                        (fun value -> dataContext.Copy(objectType = value) |> setDataContext),
                        (ProcessCoreEntityValue.DefinedTerm >> navigate),
                        imports = (fun catalog -> catalog.DefinedTerms)
                    ))
                    (NestedMetadataInput.OptionalDefinedTerm(
                        "Unit",
                        dataContext.Unit,
                        (fun value -> dataContext.Copy(unit = value) |> setDataContext),
                        (ProcessCoreEntityValue.DefinedTerm >> navigate),
                        imports = (fun catalog -> catalog.DefinedTerms)
                    ))
                    FormComponents.TextInput.TextInput(
                        dataContext.Label |> Option.defaultValue "",
                        (fun value ->
                            dataContext.Copy(label = Option.whereNot System.String.IsNullOrWhiteSpace value)
                            |> setDataContext
                        ),
                        label = "Label"
                    )
                    FormComponents.TextInput.TextInput(
                        dataContext.Description |> Option.defaultValue "",
                        (fun value ->
                            dataContext.Copy(description = Option.whereNot System.String.IsNullOrWhiteSpace value)
                            |> setDataContext
                        ),
                        label = "Description"
                    )
                    FormComponents.TextInput.TextInput(
                        dataContext.GeneratedBy |> Option.defaultValue "",
                        (fun value ->
                            dataContext.Copy(generatedBy = Option.whereNot System.String.IsNullOrWhiteSpace value)
                            |> setDataContext
                        ),
                        label = "Generated By"
                    )
                ]
            )
        ]
