namespace Swate.Components.Page.Metadata

open Feliz
open Fable.Core
open ProcessCore
open Swate.Components.Page.Metadata
open Swate.Components.Page.ObjectBrowser.Types
open Swate.Components.Primitive.LayoutComponents
open Swate.Components.Page.Metadata.FormComponents

[<Erase; Mangle(false)>]
type DataContextMetadata =

    [<ReactComponent(true)>]
    static member DataContextView
        (
            dataContext: ProcessCore.DataContext,
            setDataContext: ProcessCore.DataContext -> unit,
            ?onNavigate: ProcessCoreEntityValue -> unit
        ) =

        let navigate = defaultArg onNavigate ignore

        let updateDataContext (updateFn: ProcessCore.DataContext -> ProcessCore.DataContext) =
            let copy =
                ProcessCore.DataContext(
                    dataContext.Data,
                    ?explication = dataContext.Explication,
                    ?objectType = dataContext.ObjectType,
                    ?unit = dataContext.Unit,
                    ?label = dataContext.Label,
                    ?description = dataContext.Description,
                    ?generatedBy = dataContext.GeneratedBy
                )

            let updatedDataContext = updateFn copy
            setDataContext updatedDataContext

        LayoutComponents.Section [
            LayoutComponents.BoxedField(
                "Data Context Metadata",
                content = [
                    NestedMetadataInput.RequiredRow(
                        "Data",
                        dataContext.Data,
                        NestedMetadataInput.Data,
                        (ProcessCoreEntityValue.Data >> navigate)
                    )
                    (NestedMetadataInput.OptionalDefinedTerm(
                        "Explication",
                        dataContext.Explication,
                        (fun value ->
                            updateDataContext (fun updated ->
                                updated.Explication <- value
                                updated
                            )
                        ),
                        (ProcessCoreEntityValue.DefinedTerm >> navigate),
                        imports = (fun catalog -> catalog.DefinedTerms)
                    ))
                    (NestedMetadataInput.OptionalDefinedTerm(
                        "Object Type",
                        dataContext.ObjectType,
                        (fun value ->
                            updateDataContext (fun updated ->
                                updated.ObjectType <- value
                                updated
                            )
                        ),
                        (ProcessCoreEntityValue.DefinedTerm >> navigate),
                        imports = (fun catalog -> catalog.DefinedTerms)
                    ))
                    (NestedMetadataInput.OptionalDefinedTerm(
                        "Unit",
                        dataContext.Unit,
                        (fun value ->
                            updateDataContext (fun updated ->
                                updated.Unit <- value
                                updated
                            )
                        ),
                        (ProcessCoreEntityValue.DefinedTerm >> navigate),
                        imports = (fun catalog -> catalog.DefinedTerms)
                    ))
                    FormComponents.TextInput.TextInput(
                        dataContext.Label |> Option.defaultValue "",
                        (fun value ->
                            updateDataContext (fun updatedDataContext ->
                                updatedDataContext.Label <- Some value
                                updatedDataContext
                            )
                        ),
                        label = "Label"
                    )
                    FormComponents.TextInput.TextInput(
                        dataContext.Description |> Option.defaultValue "",
                        (fun value ->
                            updateDataContext (fun updatedDataContext ->
                                updatedDataContext.Description <- Some value
                                updatedDataContext
                            )
                        ),
                        label = "Description"
                    )
                    FormComponents.TextInput.TextInput(
                        dataContext.GeneratedBy |> Option.defaultValue "",
                        (fun value ->
                            updateDataContext (fun updatedDataContext ->
                                updatedDataContext.GeneratedBy <- Some value
                                updatedDataContext
                            )
                        ),
                        label = "Generated By"
                    )
                ]
            )
        ]
