namespace Swate.Components.Page.Metadata

open Feliz
open Fable.Core
open ProcessCore
open Swate.Components.Shared
open Swate.Components.Primitive.LayoutComponents
open Swate.Components.Page.Metadata
open Swate.Components.Page.ObjectBrowser.Types
open Swate.Components.Page.Metadata.FormComponents

[<Erase; Mangle(false)>]
type DataContextMetadata =

    [<ReactComponent(true)>]
    static member DataContextView
        (
            dataContext: ProcessCore.DataContext,
            mutate: (ARC -> unit) -> unit,
            ?onNavigate: ProcessCoreEntityValue -> unit
        ) =

        let navigate = defaultArg onNavigate ignore

        LayoutComponents.Section [
            LayoutComponents.BoxedField(
                "Data Context Metadata",
                content = [
                    NestedMetadataInput.RequiredRow(
                        "Data",
                        dataContext.Data,
                        NestedMetadataInput.Data,
                        (ProcessCoreEntityValue.Data >> navigate)
                    )
                    (NestedMetadataInput.OptionalDefinedTerm(
                        "Explication",
                        dataContext.Explication,
                        (fun value -> mutate (fun _ -> dataContext.Explication <- value)),
                        (ProcessCoreEntityValue.DefinedTerm >> navigate),
                        imports = (fun catalog -> catalog.DefinedTerms)
                    ))
                    (NestedMetadataInput.OptionalDefinedTerm(
                        "Object Type",
                        dataContext.ObjectType,
                        (fun value -> mutate (fun _ -> dataContext.ObjectType <- value)),
                        (ProcessCoreEntityValue.DefinedTerm >> navigate),
                        imports = (fun catalog -> catalog.DefinedTerms)
                    ))
                    (NestedMetadataInput.OptionalDefinedTerm(
                        "Unit",
                        dataContext.Unit,
                        (fun value -> mutate (fun _ -> dataContext.Unit <- value)),
                        (ProcessCoreEntityValue.DefinedTerm >> navigate),
                        imports = (fun catalog -> catalog.DefinedTerms)
                    ))
                    FormComponents.TextInput.TextInput(
                        dataContext.Label |> Option.defaultValue "",
                        (fun value ->
                            mutate (fun _ ->
                                dataContext.Label <- Option.whereNot System.String.IsNullOrWhiteSpace value
                            )
                        ),
                        label = "Label"
                    )
                    FormComponents.TextInput.TextInput(
                        dataContext.Description |> Option.defaultValue "",
                        (fun value ->
                            mutate (fun _ ->
                                dataContext.Description <- Option.whereNot System.String.IsNullOrWhiteSpace value
                            )
                        ),
                        label = "Description"
                    )
                    FormComponents.TextInput.TextInput(
                        dataContext.GeneratedBy |> Option.defaultValue "",
                        (fun value ->
                            mutate (fun _ ->
                                dataContext.GeneratedBy <- Option.whereNot System.String.IsNullOrWhiteSpace value
                            )
                        ),
                        label = "Generated By"
                    )
                ]
            )
        ]

type DataContextMetadata with

    [<ReactComponent>]
    static member DataContexts(contexts: ResizeArray<DataContext>, mutate: (ARC -> unit) -> unit) =
        Html.div [
            prop.className "swt:space-y-4"
            prop.children [
                for context in contexts do
                    Html.div [
                        prop.className "swt:space-y-2"
                        prop.children [ DataContextMetadata.DataContextView(context, mutate) ]
                    ]
            ]
        ]
